name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - run: go version

      - name: Get Go Paths
        id: go-paths
        run: |
          echo ::set-output name=mod_cache::$(go env GOMODCACHE)
          echo ::set-output name=build_cache::$(go env GOCACHE)

      - name: Go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.go-paths.outputs.mod_cache }}
            ${{ steps.go-paths.outputs.build_cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go modules sync
        run: go mod tidy

      - name: Run Tests
        run: make test

  release:
    name: Build Push Release
    if: startsWith( github.ref, 'refs/tags/' )
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push operator image ${{ steps.get_version.outputs.VERSION }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: cinple/gatling-operator:${{ steps.get_version.outputs.VERSION }}
          file: ./Dockerfile
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }} #push only on release
      - name: Build and push gatling-runner ${{ steps.get_version.outputs.VERSION }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: cinple/gatling:${{ steps.get_version.outputs.VERSION }}
          file: ./gatling/Dockerfile
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }} #push only on release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: gatling-operator.yaml
