name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

permissions:
  contents: write

env:
  # REGISTRY: 018471812555.dkr.ecr.eu-west-1.amazonaws.com
  REGISTRY: cinple
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - run: go version

      - name: Get Go Paths
        id: go-paths
        run: |
          echo ::set-output name=mod_cache::$(go env GOMODCACHE)
          echo ::set-output name=build_cache::$(go env GOCACHE)

      - name: Go modules and build cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-paths.outputs.mod_cache }}
            ${{ steps.go-paths.outputs.build_cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go modules sync
        run: go mod tidy

      - name: Run Tests
        run: make test

  release:
    name: Build Push Release
    if: startsWith( github.ref, 'refs/tags/' )
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1    
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Compute Release Version
        uses: AirVantage/github-actions/version-action@v101
        id: get-version
        with:
          application-name: gatling
          release-prefix: v
      - name: Create Release YAML (gatling-operator.yaml)
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
        run: make manifests-release IMG=$REGISTRY/$IMAGE_NAME:$VERSION
      - name: Build and push operator image ${{ steps.get-version.outputs.VERSION }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
          file: ./Dockerfile
          build-args: |
            VERSION=${{ steps.get-version.outputs.version }}
          push: true
      - name: Build and push gatling-runner ${{ steps.get-version.outputs.version }}
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/gatling:${{ steps.get-version.outputs.version }}
          file: ./gatling/Dockerfile
          build-args: |
            VERSION=${{ steps.get-version.outputs.version }}
          push: true
      - name: GitHub Tag & Release
        uses: AirVantage/github-actions/github-release-action@v101
        id: create-release
        with:
          version: ${{ steps.get-version.outputs.version_with_release_prefix }}
      - name: Upload Release Assets
        uses: AirVantage/github-actions/github-release-asset-action@v101
        with:
          github-release-assets: gatling-operator.yaml
          github-release-id: ${{ steps.create-release.outputs.release_id }}
    